name: BitcoinDealer
main: de.kyleonaut.dealer.BitcoinDealerPlugin
version: 1.0.0
author: kyleonaut
api-version: 1.13
depend:
  - Vault
commands:
  btc:

permissions:
  bitcoin.dealer.buy:
    default: op
  bitcoin.dealer.sell:
    default: op
  bitcoin.dealer.info:
    default: op
